import type { GuideStage } from "../types";

/**
 * Stages 1–6: strategy, household finances, the attending-income transition,
 * mortgage literacy, lender interviews, and preapproval. These run before any
 * serious touring.
 */

const strategy: GuideStage = {
  id: "strategy",
  number: 1,
  title: "Define our home-buying strategy",
  shortTitle: "Strategy",
  purpose:
    "Establish why, when, where, and what we are buying — before talking to agents or touring homes.",
  explanation:
    "Decisions made calmly now become the guardrails that protect us later, when a house we love is on the line and three other buyers want it.",
  readinessAreas: ["financial", "search"],
  suggestedWindow: { start: "2026-07", end: "2026-10" },
  personalization: [
    {
      id: "strategy.window",
      when: "always",
      text: "Our target is a {{purchaseWindow}} closing, which means offers roughly {{offerWindow}}.",
    },
    {
      id: "strategy.ownership",
      when: "always",
      text: "We expect to stay at least {{minOwnershipYears}} years, so resale and school fit matter more than a low entry price.",
    },
    {
      id: "strategy.guardrails-missing",
      when: "guardrailsIncomplete",
      text: "Some financial guardrails are still blank. Everything downstream — the offer ceiling, the readiness meters, the warnings — depends on them.",
    },
  ],
  actions: [
    {
      id: "strategy.target-period",
      title: "Confirm our target purchase period",
      why: "Every deadline in this guide counts backward from the closing window.",
      completionCriteria: "The target start and end months are saved in Settings.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "strategy.ownership-duration",
      title: "Confirm how long we expect to own this home",
      why: "A five-year horizon and a fifteen-year horizon justify very different compromises and closing costs.",
      defaultOwner: "both",
      weight: 2,
    },
    {
      id: "strategy.primary-towns",
      title: "Define our primary towns",
      why: "A short, deliberate list keeps the search honest and makes agent interviews far more useful.",
      completionCriteria: "At least two towns are marked Primary in town research.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "strategy.backup-towns",
      title: "Define our backup towns",
      why: "Inventory in one town can dry up for months. Backups keep us from stretching on price out of impatience.",
      defaultOwner: "both",
      weight: 2,
    },
    {
      id: "strategy.school-requirements",
      title: "Establish our school requirements",
      why: "Assigned schools drive both our daily life and resale, and they cannot be verified from a town name.",
      whatToGather: "The district's assignment lookup, the metric we trust, and what threshold is acceptable.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "strategy.commute-requirements",
      title: "Establish our commute requirements",
      why: "A commute that only works on paper becomes the thing we resent every weekday morning.",
      whatToGather: "Realistic door-to-door limits for NYC and Jersey City, including the walk and the parking.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "strategy.minimum-requirements",
      title: "Define our minimum home requirements",
      why: "Written must-haves are the only defense against a beautiful kitchen distracting us from a missing bedroom.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "strategy.preferences",
      title: "Define our preferences",
      why: "Separating 'would love' from 'must have' is what makes a compromise a choice instead of a regret.",
      defaultOwner: "both",
      weight: 2,
    },
    {
      id: "strategy.dealbreakers",
      title: "Define our deal-breakers",
      why: "Deal-breakers written before we fall in love are the ones we actually honor.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "strategy.renovation-tolerance",
      title: "Decide our renovation tolerance",
      why: "Renovation appetite changes which listings are worth touring and how much cash we must hold back.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "strategy.comfortable-range",
      title: "Establish our comfortable purchase range",
      why: "This is the band we shop in, not the maximum a lender will allow.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "strategy.routine-ceiling",
      title: "Establish our routine offer ceiling",
      why: "The price above which an offer needs a specific, deliberate reason — not just enthusiasm.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "strategy.walk-away-price",
      title: "Establish our absolute walk-away price",
      why: "The number we agree to now, in a quiet room, is the one that protects us in a bidding war.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "strategy.comfortable-payment",
      title: "Establish our comfortable monthly payment",
      why: "Monthly cost, not purchase price, is what we actually live with for the next decade.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "strategy.max-payment",
      title: "Establish our maximum monthly payment",
      why: "A ceiling on the payment keeps a low rate quote from quietly raising our price range.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "strategy.min-reserve",
      title: "Establish our minimum post-closing reserve",
      why: "The cash that must still exist the day after closing — before a single repair or emergency.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "strategy.preferred-reserve",
      title: "Establish our preferred post-closing reserve",
      why: "The reserve we would like to keep, which tells us when a house is affordable rather than merely possible.",
      defaultOwner: "both",
      weight: 5,
    },
  ],
  decisions: [
    {
      id: "strategy.why-buying",
      prompt: "Why are we buying now rather than continuing to rent?",
      help: "Write it plainly. This is what we reread when the search gets frustrating.",
      requiresBothSpouses: true,
    },
    {
      id: "strategy.location-strategy",
      prompt: "What is our primary and backup location strategy, and what would make us change it?",
      requiresBothSpouses: true,
    },
    {
      id: "strategy.biggest-compromise",
      prompt: "Which compromise are we most willing to make — price, size, condition, commute, or town?",
      help: "Naming this in advance prevents the compromise from being chosen for us by whichever house we see first.",
      requiresBothSpouses: true,
    },
    {
      id: "strategy.renovation-appetite",
      prompt: "How much renovation work will we genuinely take on in the first two years?",
      suggestions: ["Turnkey only", "Cosmetic work", "Moderate renovation", "Major renovation"],
      requiresBothSpouses: true,
    },
  ],
  questionSets: [
    {
      audience: "ourselves",
      title: "Questions to answer together",
      questions: [
        {
          id: "strategy.q.five-years",
          question: "Where do we expect to be, professionally and personally, in five years?",
          listenFor: "A job change or a second child changes the minimum requirements more than the budget does.",
        },
        {
          id: "strategy.q.one-income",
          question: "Could we carry this payment on one income for six months if we had to?",
          listenFor: "If the answer is no, the comfortable payment is set too high.",
        },
        {
          id: "strategy.q.regret",
          question: "What would make us regret this purchase in three years?",
        },
      ],
    },
  ],
  documents: [
    { label: "Written must-haves, preferences, and deal-breakers", category: "identification", note: "Kept in Settings → Home preferences." },
  ],
  resourceSlugs: ["hud-buying-a-home", "cfpb-owning-a-home"],
  mistakes: [
    "Setting a price range from a lender's maximum instead of our own budget.",
    "Deciding the walk-away price after seeing a house we love.",
    "Treating a town's reputation as proof of the assigned school.",
    "Skipping backup towns and then overpaying out of impatience.",
    "Leaving the reserve requirement vague so it can quietly be spent.",
  ],
  completionCriteria: [
    { id: "strategy.c.criteria-approved", label: "Both of us have approved the home criteria", autoCheck: "bothApprovedStrategyDecisions" },
    { id: "strategy.c.guardrails", label: "Financial guardrails are saved", autoCheck: "guardrailsComplete" },
    { id: "strategy.c.dealbreakers", label: "Deal-breakers are documented", autoCheck: "dealbreakersDocumented" },
    { id: "strategy.c.locations", label: "Primary and backup town strategy is documented", autoCheck: "townStrategyDocumented" },
  ],
  relatedTools: [
    { label: "Household profile", href: "/settings", description: "Names, income, target purchase window." },
    { label: "Home preferences", href: "/settings", description: "Must-haves, preferences, deal-breakers." },
    { label: "Financial guardrails", href: "/settings", description: "Price, payment, and reserve limits." },
    { label: "Town research", href: "/journey/town-research", description: "Primary and backup towns." },
    { label: "Financial planner", href: "/finances", description: "Test what a price range really costs." },
  ],
  order: 1,
  version: 1,
};

const finances: GuideStage = {
  id: "finances",
  number: 2,
  title: "Prepare our finances",
  shortTitle: "Finances",
  purpose:
    "Make the household financially and operationally ready before a lender ever looks at us.",
  explanation:
    "Underwriting is mostly a paperwork exercise. The households that find it painless are the ones that assembled the paperwork months earlier.",
  readinessAreas: ["financial", "mortgage"],
  suggestedWindow: { start: "2026-08", end: "2027-01" },
  personalization: [
    {
      id: "finances.childcare",
      when: "childcareMissing",
      text: "Our childcare cost is still unknown. Until it is entered, every monthly-payment figure in the app is optimistic.",
    },
    {
      id: "finances.reserve",
      when: "always",
      text: "We need at least {{minReserve}} left after closing, and would prefer {{preferredReserve}}. That comes off the top, before the down payment.",
    },
    {
      id: "finances.taxable",
      when: "hasTaxableInvestments",
      text: "Most of our house money sits in taxable investments ({{taxableInvestments}}). How much of that is genuinely available — and what selling costs in tax — is a decision, not a given.",
    },
    {
      id: "finances.credit-gap",
      when: "creditScoreGap",
      text: "Our credit scores differ by {{creditScoreGap}} points. Joint applications are usually priced off the lower one, so ask each lender how they handle it.",
    },
  ],
  actions: [
    {
      id: "finances.credit-reports",
      title: "Review both credit reports",
      why: "Errors take weeks to correct, and they are cheapest to fix long before an application.",
      whatToGather: "A full report for each of us from the free annual source.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "finances.credit-scores",
      title: "Record both credit scores",
      why: "Joint borrowers are usually priced off the lower score. Knowing the gap early is worth real money.",
      completionCriteria: "Both scores are entered in Settings.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "finances.debts",
      title: "Review all outstanding debts",
      why: "Every monthly obligation reduces the loan we qualify for, whether or not it feels significant.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "finances.vehicle-loans",
      title: "Review vehicle-loan balances and remaining payments",
      why: "A car loan with a few payments left is treated very differently from one with three years to run — and lenders vary on this.",
      whatToGather: "Payoff balances, monthly payments, and remaining terms.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "finances.childcare",
      title: "Determine our actual childcare costs",
      why: "Childcare is often the single largest line item after the mortgage, and it is currently a blank in our plan.",
      whatToGather: "Real quotes from the options we would actually use in our target towns.",
      completionCriteria: "A monthly childcare figure is saved in Settings.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "finances.spending-tracking",
      title: "Track three months of household spending",
      why: "The comfortable payment should be built on what we actually spend, not on what we intend to spend.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "finances.taxable-availability",
      title: "Decide how much of our taxable investments may be used",
      why: "Naming the amount converts a vague pile of money into a real house fund with a limit.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "finances.tax-lots",
      title: "Review capital gains and investment tax lots",
      why: "Selling to fund a down payment has a tax cost that should be known before, not discovered in April.",
      whatToGather: "Cost-basis and lot detail from the brokerage.",
      completionCriteria: "We understand the approximate tax cost of raising our down payment.",
      defaultOwner: "both",
      weight: 3,
      conditional: "Consider confirming the specifics with a tax professional.",
    },
    {
      id: "finances.derisk-house-money",
      title: "Move near-term house money somewhere lower-volatility",
      why: "Money needed within roughly a year has little time to recover from a drawdown.",
      defaultOwner: "both",
      weight: 5,
      conditional: "This is a personal risk decision; a financial professional can help weigh it.",
    },
    {
      id: "finances.down-payment",
      title: "Define our down-payment amount",
      why: "It determines the loan size, whether mortgage insurance applies, and how much cash is left afterward.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "finances.closing-costs",
      title: "Allocate closing costs",
      why: "Closing costs are cash on top of the down payment and are routinely underestimated.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "finances.moving-budget",
      title: "Define our moving budget",
      why: "Moving costs land in the same weeks as closing, when cash is tightest.",
      defaultOwner: "both",
      weight: 2,
    },
    {
      id: "finances.repair-budget",
      title: "Define our immediate repair budget",
      why: "Nearly every older New Jersey house needs something in the first ninety days.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "finances.preserve-reserves",
      title: "Confirm the minimum and preferred reserves are preserved in every plan",
      why: "A house is only affordable if it is still affordable the day after we buy it.",
      completionCriteria: "The reserve figures are saved and our working scenarios respect them.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "finances.document-folder",
      title: "Create a mortgage document folder",
      why: "One folder, one place. Underwriting requests arrive with short deadlines.",
      whatToGather: "A secure folder outside this app — the app only indexes what exists and where.",
      defaultOwner: "buyer1",
      weight: 2,
    },
    {
      id: "finances.tax-returns",
      title: "Gather tax returns",
      why: "Two years is the usual request, and self-employment or bonus income can trigger more.",
      whatToGather: "The last two years of complete federal returns, all schedules.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "finances.w2s",
      title: "Gather W-2 forms",
      why: "Standard proof of income history for both of us.",
      whatToGather: "The last two years of W-2s for each borrower.",
      defaultOwner: "both",
      weight: 2,
    },
    {
      id: "finances.pay-statements",
      title: "Gather pay statements",
      why: "Lenders want recent, consecutive statements and will re-request them close to closing.",
      whatToGather: "The most recent 30 days for each borrower.",
      defaultOwner: "both",
      weight: 2,
    },
    {
      id: "finances.bank-statements",
      title: "Gather bank statements",
      why: "Every large or unusual deposit will need a paper trail; knowing that early prevents scrambling.",
      whatToGather: "Two months of complete statements, all pages, for every account used.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "finances.investment-statements",
      title: "Gather investment statements",
      why: "These prove both the down-payment source and the reserves.",
      whatToGather: "Two months of statements for taxable and retirement accounts.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "finances.identification",
      title: "Gather identification documents",
      why: "Trivial to collect, and genuinely delays a file when missing.",
      defaultOwner: "both",
      weight: 1,
    },
    {
      id: "finances.employment-verification",
      title: "Gather employment verification",
      why: "Employment is verified at application and again shortly before closing.",
      whatToGather: "Employer contact details for verification; the attending contract is tracked in stage 3.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "finances.avoid-new-debt",
      title: "Avoid new debt and unnecessary credit applications",
      why: "A new car loan or credit line between preapproval and closing can undo the approval outright.",
      completionCriteria: "We have agreed not to open new credit until after closing.",
      defaultOwner: "both",
      weight: 5,
    },
  ],
  decisions: [
    {
      id: "finances.house-fund-size",
      prompt: "How much of our investments and savings are we willing to convert into the house fund?",
      requiresBothSpouses: true,
    },
    {
      id: "finances.reserve-floor",
      prompt: "What is the reserve we will not go below, no matter how good the house is?",
      requiresBothSpouses: true,
    },
    {
      id: "finances.derisk-decision",
      prompt: "Are we moving near-term house money out of volatile investments, and when?",
      help: "The app does not give investment advice. Record what we decided and why.",
      requiresBothSpouses: true,
    },
  ],
  questionSets: [
    {
      audience: "lender",
      title: "Questions worth asking early",
      questions: [
        {
          id: "finances.q.doc-list",
          question: "What is your complete document list for our situation?",
          listenFor: "A specific list, not 'the usual stuff'.",
        },
        {
          id: "finances.q.deposits",
          question: "How do you want large deposits and gift funds documented?",
        },
        {
          id: "finances.q.car-loan",
          question: "How will you treat our car payment and remaining balance?",
        },
      ],
    },
  ],
  documents: [
    { label: "Federal tax returns — last two years", category: "taxes" },
    { label: "W-2 forms — last two years", category: "income" },
    { label: "Pay statements — most recent 30 days", category: "income" },
    { label: "Bank statements — two months, all pages", category: "bank-statements" },
    { label: "Investment account statements — two months", category: "investment-statements" },
    { label: "Driver's licence or passport for both borrowers", category: "identification" },
    { label: "Employment verification contact details", category: "employment" },
    { label: "Credit reports for both borrowers", category: "credit" },
  ],
  resourceSlugs: ["cfpb-prepare-to-shop", "cfpb-owning-a-home"],
  mistakes: [
    "Opening a new credit line or financing a car during the process.",
    "Moving money between accounts without keeping the paper trail.",
    "Counting retirement accounts as available closing cash.",
    "Budgeting the payment and forgetting maintenance, utilities, and childcare.",
    "Leaving the down payment invested in something volatile weeks before closing.",
  ],
  completionCriteria: [
    { id: "finances.c.childcare", label: "A real childcare estimate is recorded", autoCheck: "childcareRecorded" },
    { id: "finances.c.house-fund", label: "The house fund is defined and its source identified", autoCheck: "houseFundIdentified" },
    { id: "finances.c.reserves", label: "Minimum and preferred reserves are saved", autoCheck: "reservesSet" },
    { id: "finances.c.documents", label: "The core document set is gathered", autoCheck: "coreDocumentsGathered" },
    { id: "finances.c.credit", label: "Both credit scores are recorded", autoCheck: "creditScoresRecorded" },
  ],
  relatedTools: [
    { label: "Financial settings", href: "/settings", description: "Assets, debts, expenses, guardrails." },
    { label: "Financial planner", href: "/finances", description: "Scenario testing with real numbers." },
    { label: "Document index", href: "/timeline?tab=documents", description: "Track what exists and where it lives." },
  ],
  order: 2,
  version: 1,
};

const attending: GuideStage = {
  id: "attending",
  number: 3,
  title: "Prepare for the attending-income transition",
  shortTitle: "Attending income",
  purpose:
    "Make sure the transition from resident to attending physician can be properly considered by a lender.",
  explanation:
    "Future employment income is a normal thing for lenders to evaluate — but every lender treats it differently, and the differences are large enough to change which houses are reachable.",
  readinessAreas: ["financial", "mortgage"],
  suggestedWindow: { start: "2026-09", end: "2027-04" },
  warnings: [
    {
      tone: "critical",
      text: "Do not base an offer on expected attending income until a lender confirms in writing how that income will be treated.",
    },
  ],
  personalization: [
    {
      id: "attending.no-salary",
      when: "attendingSalaryMissing",
      text: "No expected attending salary is recorded yet. Enter a range and label it uncertain — an explicit estimate is far more useful than a blank.",
    },
    {
      id: "attending.no-contract",
      when: "attendingContractMissing",
      text: "No signed contract is recorded. Most lenders that count future income want a signed contract in hand, and our timing depends on that.",
    },
    {
      id: "attending.timing-risk",
      when: "attendingContractLate",
      text: "Our target closing is {{purchaseWindow}}. Without a signed contract by around February 2027, financing timing becomes the biggest risk in the plan.",
    },
    {
      id: "attending.treatment-unconfirmed",
      when: "attendingTreatmentUnconfirmed",
      text: "No lender has confirmed in writing how the attending income will be treated. Until one does, treat the higher income as unavailable for qualifying.",
    },
  ],
  actions: [
    {
      id: "attending.job-search-status",
      title: "Record the attending job-search status",
      why: "The financing plan depends on where this stands, not on where we hope it stands.",
      defaultOwner: "buyer2",
      weight: 3,
    },
    {
      id: "attending.expected-location",
      title: "Record the expected job location",
      why: "It determines whether our target towns still make sense at all.",
      defaultOwner: "buyer2",
      weight: 5,
    },
    {
      id: "attending.expected-start",
      title: "Record the expected start date",
      why: "Lenders cap how long after closing employment may begin. This date decides which lenders are usable.",
      defaultOwner: "buyer2",
      weight: 8,
    },
    {
      id: "attending.expected-salary",
      title: "Record the expected base salary, as a range if uncertain",
      why: "An explicit labeled estimate lets us plan; a blank field silently defaults our plan to resident income.",
      defaultOwner: "buyer2",
      weight: 5,
    },
    {
      id: "attending.shift-structure",
      title: "Record the expected shift structure",
      why: "Shift load shapes childcare costs and what commute is survivable.",
      defaultOwner: "buyer2",
      weight: 2,
    },
    {
      id: "attending.bonus-structure",
      title: "Record the expected bonus or incentive structure",
      why: "Variable compensation is usually treated conservatively — often ignored entirely without a history.",
      defaultOwner: "buyer2",
      weight: 2,
    },
    {
      id: "attending.contract-signed",
      title: "Record the signed employment contract status",
      why: "For most lenders, this is the single document that unlocks using future income.",
      whatToGather: "The fully executed contract, with start date and compensation.",
      defaultOwner: "buyer2",
      weight: 8,
      targetMonth: "2027-02",
    },
    {
      id: "attending.contingencies",
      title: "Record contract contingencies",
      why: "Contingencies such as licensure or credentialing can matter to underwriting as much as the salary.",
      defaultOwner: "buyer2",
      weight: 3,
    },
    {
      id: "attending.credentialing",
      title: "Track credentialing status",
      why: "Credentialing delays push back the start date, which can push back what a lender will accept.",
      defaultOwner: "buyer2",
      weight: 3,
    },
    {
      id: "attending.lender-acceptance",
      title: "Get written confirmation of how each lender treats future employment income",
      why: "Verbal reassurance from a loan officer is not a commitment, and staff turn over.",
      completionCriteria: "At least one lender has confirmed the treatment in writing.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "attending.max-gap",
      title: "Record the maximum period each lender allows between closing and the start date",
      why: "This single number often decides which lenders can serve us at all.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "attending.required-reserves",
      title: "Record each lender's reserve requirement for future-income files",
      why: "Future-income approvals commonly require several months of reserves on top of everything else.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "attending.required-docs",
      title: "Record the required employment documentation",
      why: "Knowing the exact list early avoids a scramble during underwriting.",
      defaultOwner: "both",
      weight: 3,
    },
  ],
  decisions: [
    {
      id: "attending.plan-b",
      prompt: "If the contract is not signed in time, do we delay the purchase or qualify on current income alone?",
      help: "Deciding this in advance keeps a deadline from making the decision for us.",
      requiresBothSpouses: true,
    },
    {
      id: "attending.income-basis",
      prompt: "Which income are we using for our own guardrails — current, expected attending, or a blend?",
      help: "Our guardrails can be more conservative than what a lender will allow. That is the point of them.",
      requiresBothSpouses: true,
    },
  ],
  questionSets: [
    {
      audience: "lender",
      title: "Attending-income questions for every lender",
      intro: "Ask each of these and record the answer in writing on the lender's record.",
      questions: [
        {
          id: "attending.q.future-income",
          question: "Can future attending income be used to qualify, and under what conditions?",
          listenFor: "A specific policy, ideally quoted from guidelines — not 'we can usually work with that'.",
        },
        {
          id: "attending.q.contract-sufficient",
          question: "Is a signed employment contract sufficient, or are pay statements required before closing?",
        },
        {
          id: "attending.q.gap",
          question: "How many days after closing may employment begin?",
        },
        {
          id: "attending.q.em-eligible",
          question: "Is emergency medicine eligible under your physician programme?",
        },
        {
          id: "attending.q.reserves",
          question: "What cash reserves are required when qualifying on a future contract?",
        },
        {
          id: "attending.q.bonus",
          question: "How is contract bonus or incentive compensation treated with no earnings history?",
        },
        {
          id: "attending.q.written",
          question: "Will you put that treatment in writing for our file?",
          listenFor: "Reluctance here is itself an answer.",
        },
      ],
    },
  ],
  documents: [
    { label: "Signed attending employment contract", category: "attending-contract" },
    { label: "Offer letter and any amendments", category: "attending-contract" },
    { label: "Credentialing or licensure correspondence", category: "employment" },
    { label: "Written lender confirmation of income treatment", category: "preapproval" },
  ],
  resourceSlugs: ["cfpb-explore-loan-choices", "cfpb-prepare-to-shop"],
  mistakes: [
    "Making an offer that only works on attending income before a lender has confirmed it in writing.",
    "Assuming every physician-mortgage lender treats future income the same way.",
    "Forgetting that the start date, not the signing date, drives the lender's limit.",
    "Counting an expected bonus that has no earnings history.",
    "Letting a verbal 'that won't be a problem' stand in for a written policy.",
  ],
  completionCriteria: [
    { id: "attending.c.salary", label: "An expected salary figure or range is recorded", autoCheck: "attendingSalaryRecorded" },
    { id: "attending.c.start", label: "An expected start date is recorded", autoCheck: "attendingStartRecorded" },
    { id: "attending.c.contract", label: "The contract status is current", autoCheck: "attendingContractSigned" },
    { id: "attending.c.written", label: "A lender has confirmed income treatment in writing", autoCheck: "attendingTreatmentConfirmed" },
  ],
  relatedTools: [
    { label: "Attending transition tracker", href: "/journey/attending", description: "On this page, below." },
    { label: "Lenders", href: "/lenders", description: "Record each lender's written answer." },
    { label: "Financial planner", href: "/finances", description: "Model current vs. attending income." },
    { label: "Document index", href: "/timeline?tab=documents", description: "Note where the contract is stored." },
  ],
  order: 3,
  version: 1,
};

const mortgageOptions: GuideStage = {
  id: "mortgage-options",
  number: 4,
  title: "Learn our mortgage options",
  shortTitle: "Mortgage options",
  purpose: "Understand the available loan structures well enough to ask good questions.",
  explanation:
    "The goal is not to pick a loan from a website. It is to walk into a lender conversation knowing which tradeoffs to probe.",
  readinessAreas: ["mortgage"],
  suggestedWindow: { start: "2026-10", end: "2027-01" },
  personalization: [
    {
      id: "mortgage-options.jumbo",
      when: "priceRangeLikelyJumbo",
      text: "At our comfortable range ({{comfortableRange}}), conforming, high-balance, and jumbo limits are all potentially in play. Which bucket a loan falls into changes the rate, the reserves, and the documentation.",
    },
    {
      id: "mortgage-options.physician",
      when: "always",
      text: "A physician mortgage may allow a lower down payment without mortgage insurance — but it is a product with tradeoffs, not automatically the best choice for us.",
    },
  ],
  actions: [
    {
      id: "mortgage-options.read-concepts",
      title: "Work through the loan-structure explanations below",
      why: "Twenty minutes here makes every lender conversation shorter and more useful.",
      defaultOwner: "both",
      weight: 2,
    },
    {
      id: "mortgage-options.loan-limits",
      title: "Look up the current conforming and high-balance loan limits for our target counties",
      why: "The limit decides whether we are shopping a conventional, high-balance, or jumbo loan.",
      whatToGather: "The current year's limits for each county on our list.",
      defaultOwner: "buyer1",
      weight: 3,
    },
    {
      id: "mortgage-options.shortlist-structures",
      title: "Shortlist the loan structures worth quoting",
      why: "Comparing two or three structures keeps the choice concrete rather than theoretical.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "mortgage-options.down-payment-scenarios",
      title: "Model our realistic down-payment options",
      why: "Down payment trades against reserves, mortgage insurance, and monthly cost all at once.",
      completionCriteria: "At least two down-payment scenarios are saved in the planner.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "mortgage-options.rate-type",
      title: "Decide our starting position on fixed versus adjustable",
      why: "It is far easier to evaluate a quote when we already know which risk we are willing to hold.",
      defaultOwner: "both",
      weight: 3,
    },
  ],
  decisions: [
    {
      id: "mortgage-options.structures-to-quote",
      prompt: "Which loan structures will we ask every lender to quote?",
      suggestions: ["Physician", "Conventional", "High-balance conventional", "Jumbo"],
      requiresBothSpouses: true,
    },
    {
      id: "mortgage-options.rate-type-decision",
      prompt: "Fixed or adjustable — and what would change our mind?",
      help: "Tie this to how long we expect to own the home.",
      requiresBothSpouses: true,
    },
    {
      id: "mortgage-options.points",
      prompt: "Are we willing to pay points, and what break-even period would justify it?",
    },
  ],
  questionSets: [
    {
      audience: "lender",
      title: "Structure questions",
      questions: [
        { id: "mortgage-options.q.structures", question: "Which structures do you recommend for our profile, and why those?" },
        { id: "mortgage-options.q.pmi", question: "At what down payment does mortgage insurance disappear on each option?" },
        { id: "mortgage-options.q.limits", question: "What are the loan limits that apply in our target counties?" },
        { id: "mortgage-options.q.arm-terms", question: "If adjustable: what are the caps, the index, the margin, and the first adjustment date?" },
        { id: "mortgage-options.q.points-breakeven", question: "What is the break-even period on any points you are quoting?" },
      ],
    },
  ],
  documents: [
    { label: "Written rate and fee sheets from each conversation", category: "lender-quotes" },
    { label: "Loan Estimates once formally quoted", category: "loan-estimate" },
  ],
  resourceSlugs: ["cfpb-explore-loan-choices", "cfpb-owning-a-home", "cfpb-prepare-to-shop"],
  mistakes: [
    "Comparing loans on interest rate alone and ignoring fees, points, and mortgage insurance.",
    "Assuming a physician mortgage is automatically the best option.",
    "Ignoring which side of the loan limit a purchase price falls on.",
    "Taking an adjustable rate without knowing the caps and first adjustment date.",
    "Paying points without calculating the break-even against how long we will own.",
  ],
  completionCriteria: [
    { id: "mortgage-options.c.structures", label: "We have chosen which structures to quote", autoCheck: "loanStructuresChosen" },
    { id: "mortgage-options.c.scenarios", label: "At least two down-payment scenarios are saved", autoCheck: "twoScenariosSaved" },
    { id: "mortgage-options.c.rate-type", label: "We have a starting position on fixed vs. adjustable", autoCheck: "rateTypeDecided" },
  ],
  relatedTools: [
    { label: "Financial planner", href: "/finances", description: "Model each structure side by side." },
    { label: "Lenders", href: "/lenders", description: "Record what each lender quotes." },
    { label: "Resource library", href: "/resources", description: "Primary-source explanations." },
  ],
  order: 4,
  version: 1,
};

const lenderInterviews: GuideStage = {
  id: "lender-interviews",
  number: 5,
  title: "Interview lenders",
  shortTitle: "Lender interviews",
  purpose:
    "Identify qualified lenders and learn how each one will actually treat our financial profile.",
  explanation:
    "Rate shopping comes later. The first conversation is about eligibility and policy — especially around the attending contract — because a great rate from a lender who cannot use our income is worth nothing.",
  readinessAreas: ["mortgage", "team"],
  suggestedWindow: { start: "2026-11", end: "2027-02" },
  personalization: [
    {
      id: "lender-interviews.count",
      when: "fewLenders",
      text: "We have {{lenderCount}} lender(s) recorded. Four gives a real spread of policies, especially on the attending contract.",
    },
    {
      id: "lender-interviews.attending",
      when: "attendingTreatmentUnconfirmed",
      text: "The deciding question for us is future-income treatment. Ask it first in every call — it eliminates unsuitable lenders in two minutes.",
    },
  ],
  actions: [
    {
      id: "lender-interviews.shortlist",
      title: "Build a shortlist of at least four lenders",
      why: "Policies on future income and reserves vary more between lenders than rates do.",
      completionCriteria: "Four or more lenders are recorded.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "lender-interviews.physician-lenders",
      title: "Include physician-mortgage lenders",
      why: "These programmes exist precisely for the situation we are in.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "lender-interviews.conventional-lender",
      title: "Include a conventional or high-balance lender",
      why: "A conventional quote is the benchmark that shows what a physician loan actually costs.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "lender-interviews.jumbo-lender",
      title: "Include a jumbo lender where relevant",
      why: "At our price range, some purchases will land above the high-balance limit.",
      defaultOwner: "both",
      weight: 3,
      conditional: "Only if our range exceeds the county limit.",
    },
    {
      id: "lender-interviews.strategy-calls",
      title: "Hold initial strategy conversations",
      why: "An early conversation is about fit and policy — it is not an application and not an approval.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "lender-interviews.doc-requirements",
      title: "Record each lender's documentation requirements",
      why: "Lists differ, and the differences reveal how carefully a lender will underwrite the file.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "lender-interviews.contract-requirements",
      title: "Record each lender's attending-contract requirements",
      why: "This is our deciding factor. It belongs in writing on each lender's record.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "lender-interviews.reserve-requirements",
      title: "Record each lender's reserve requirements",
      why: "Reserve requirements can quietly reduce the down payment we can afford to make.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "lender-interviews.compare-costs",
      title: "Compare rates and total costs at the appropriate time",
      why: "Rates are only comparable when quoted close together on the same scenario.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "lender-interviews.select-for-preapproval",
      title: "Select the lenders we will take to formal preapproval",
      why: "Two credible preapprovals give us leverage and a fallback.",
      defaultOwner: "both",
      weight: 5,
    },
  ],
  decisions: [
    {
      id: "lender-interviews.finalists",
      prompt: "Which lenders are our finalists for formal preapproval, and why those?",
      requiresBothSpouses: true,
    },
    {
      id: "lender-interviews.tradeoff",
      prompt: "If the lender with the best rate cannot use the attending contract, which do we choose?",
      requiresBothSpouses: true,
    },
  ],
  questionSets: [
    {
      audience: "lender",
      title: "Lender interview checklist",
      intro:
        "Ask all of these, and record every answer against the lender's record so the comparison stays honest.",
      questions: [
        { id: "lender.q.physician-nj", question: "Do you offer physician mortgages in New Jersey?" },
        { id: "lender.q.em-eligible", question: "Is emergency medicine eligible?" },
        { id: "lender.q.future-income", question: "Can future attending income be used?" },
        { id: "lender.q.start-gap", question: "How far after closing may employment begin?" },
        { id: "lender.q.contract-sufficient", question: "Is a signed contract sufficient?" },
        { id: "lender.q.pay-stubs", question: "Are pay statements required before closing?" },
        { id: "lender.q.down-payments", question: "What down payments are available?" },
        { id: "lender.q.mi-required", question: "Is mortgage insurance required?" },
        { id: "lender.q.max-loan", question: "What are the maximum loan amounts?" },
        { id: "lender.q.reserves", question: "What cash reserves are required?" },
        { id: "lender.q.taxable-treatment", question: "How are taxable investments treated?" },
        { id: "lender.q.car-payments", question: "How are car payments treated?" },
        { id: "lender.q.credit-score-used", question: "What credit score is used for joint borrowers?" },
        { id: "lender.q.lower-score-adjustments", question: "Are there rate or fee adjustments for the lower score?" },
        { id: "lender.q.rate-type", question: "Is the rate fixed or adjustable?" },
        { id: "lender.q.points", question: "Are points required?" },
        { id: "lender.q.fees", question: "What lender fees apply?" },
        { id: "lender.q.lock-length", question: "How long is the rate lock?" },
        { id: "lender.q.recast", question: "Can the loan be recast?" },
        { id: "lender.q.prepayment", question: "Is there a prepayment penalty?" },
        { id: "lender.q.prepare-now", question: "What documentation should we prepare now?" },
      ],
    },
  ],
  documents: [
    { label: "Written answers from each lender interview", category: "lender-quotes" },
    { label: "Rate and fee sheets", category: "lender-quotes" },
  ],
  resourceSlugs: ["cfpb-prepare-to-shop", "cfpb-explore-loan-choices", "cfpb-prequal-vs-preapproval"],
  mistakes: [
    "Interviewing one lender and treating that as the market.",
    "Asking about rate before asking whether the lender can use our income at all.",
    "Letting each lender quote a different purchase price so nothing is comparable.",
    "Not writing down answers, then relying on memory weeks later.",
    "Assuming a referral from an agent is automatically the best option for us.",
  ],
  completionCriteria: [
    { id: "lender-interviews.c.four", label: "At least four lenders are recorded", autoCheck: "fourLendersRecorded" },
    { id: "lender-interviews.c.interviews", label: "Interview answers are captured for the finalists", autoCheck: "lenderInterviewsCaptured" },
    { id: "lender-interviews.c.attending", label: "Attending-contract treatment is recorded for each lender", autoCheck: "attendingTreatmentConfirmed" },
    { id: "lender-interviews.c.finalists", label: "Finalists for formal preapproval are chosen", autoCheck: "lenderFinalistsChosen" },
  ],
  relatedTools: [
    { label: "Lenders", href: "/lenders", description: "Quotes, interview answers, comparison." },
    { label: "Professionals", href: "/professionals", description: "Loan-officer contact records." },
    { label: "Financial planner", href: "/finances", description: "Quote the same scenario to everyone." },
  ],
  order: 5,
  version: 1,
};

const preapproval: GuideStage = {
  id: "preapproval",
  number: 6,
  title: "Obtain mortgage preapproval",
  shortTitle: "Preapproval",
  purpose: "Obtain a credible preapproval before making active offers.",
  explanation:
    "Sellers take offers seriously in proportion to how thoroughly the buyer's lender has already reviewed them. The four levels below are not interchangeable.",
  readinessAreas: ["mortgage", "offer"],
  suggestedWindow: { start: "2027-01", end: "2027-04" },
  warnings: [
    {
      tone: "caution",
      text: "A preapproval amount is not our spending budget. Our own guardrails stay in control even when a lender approves more.",
    },
  ],
  personalization: [
    {
      id: "preapproval.none",
      when: "noPreapproval",
      text: "No preapproval is recorded yet. Touring in earnest without one usually costs us the first house we actually want.",
    },
    {
      id: "preapproval.guardrails",
      when: "always",
      text: "Whatever a lender approves, our routine ceiling is {{routineCeiling}} and our walk-away price is {{walkAwayPrice}}.",
    },
    {
      id: "preapproval.expiring",
      when: "preapprovalExpiringSoon",
      text: "A preapproval on file expires within 60 days. Ask the lender what refreshing it requires before it lapses mid-search.",
    },
  ],
  actions: [
    {
      id: "preapproval.choose-lenders",
      title: "Choose the lenders for formal preapproval",
      why: "Two is usually right: one primary, one credible alternative.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "preapproval.submit-documents",
      title: "Submit the full document package",
      why: "The completeness of what we submit determines how much the preapproval is worth.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "preapproval.credit-reviewed",
      title: "Confirm credit has been reviewed",
      why: "A preapproval issued without a credit pull is closer to a guess.",
      defaultOwner: "lender",
      weight: 3,
    },
    {
      id: "preapproval.income-reviewed",
      title: "Confirm income has been reviewed",
      why: "Including how our attending contract was treated in the calculation.",
      defaultOwner: "lender",
      weight: 5,
    },
    {
      id: "preapproval.assets-debts-reviewed",
      title: "Confirm assets and debts have been reviewed",
      why: "This is what separates a real preapproval from a prequalification.",
      defaultOwner: "lender",
      weight: 3,
    },
    {
      id: "preapproval.record-terms",
      title: "Record the maximum loan amount, rate, and closing-cost estimate",
      why: "These are the numbers we will be held to, so they belong on the record.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "preapproval.record-assumptions",
      title: "Confirm the tax and insurance assumptions the lender used",
      why: "New Jersey property taxes vary enormously; an optimistic assumption inflates the approval.",
      completionCriteria: "The assumed annual taxes and insurance are recorded.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "preapproval.record-expiration",
      title: "Record the expiration or refresh date",
      why: "An expired letter at the wrong moment can cost us a house.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "preapproval.record-restrictions",
      title: "Record property-type and loan-limit restrictions",
      why: "Some approvals quietly exclude condos, multi-family, or specific counties.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "preapproval.fully-underwritten",
      title: "Ask whether a fully underwritten preapproval is available",
      why: "In a competitive offer, this is one of the few things that genuinely strengthens a bid.",
      defaultOwner: "both",
      weight: 5,
    },
  ],
  decisions: [
    {
      id: "preapproval.spending-limit",
      prompt: "If we are preapproved for more than our comfortable range, what do we do?",
      help: "The intended answer is 'nothing changes'. Write down why.",
      requiresBothSpouses: true,
    },
    {
      id: "preapproval.primary-lender",
      prompt: "Which preapproval do we lead with when making offers, and why?",
      requiresBothSpouses: true,
    },
  ],
  questionSets: [
    {
      audience: "lender",
      title: "Preapproval questions",
      questions: [
        { id: "preapproval.q.level", question: "Is this a prequalification, a preapproval, or a fully underwritten approval?" },
        { id: "preapproval.q.reviewed", question: "Exactly what did you review — credit, income, assets, the contract?" },
        { id: "preapproval.q.assumptions", question: "What property tax and insurance figures did you assume?" },
        { id: "preapproval.q.expires", question: "When does this expire, and what is needed to refresh it?" },
        { id: "preapproval.q.restrictions", question: "Are any property types or counties excluded?" },
        { id: "preapproval.q.conditions", question: "What conditions remain outstanding on the file?" },
        { id: "preapproval.q.reissue", question: "Can you reissue the letter at a specific offer amount, quickly?" },
      ],
    },
  ],
  documents: [
    { label: "Preapproval letter", category: "preapproval" },
    { label: "Written confirmation of attending-income treatment", category: "preapproval" },
    { label: "Complete submitted document package", category: "income" },
  ],
  resourceSlugs: ["cfpb-preapproval-letter", "cfpb-prequal-vs-preapproval", "cfpb-owning-a-home"],
  mistakes: [
    "Treating a preapproval as a guaranteed loan.",
    "Letting the preapproval amount become the shopping budget.",
    "Not checking which property tax figure the lender assumed.",
    "Letting the letter expire in the middle of the search.",
    "Believing we are committed to the lender that issued the preapproval.",
  ],
  completionCriteria: [
    { id: "preapproval.c.exists", label: "A formal preapproval is recorded", autoCheck: "formalPreapprovalRecorded" },
    { id: "preapproval.c.reviews", label: "Credit, income, assets, and debts were all reviewed", autoCheck: "preapprovalReviewsComplete" },
    { id: "preapproval.c.terms", label: "Maximum loan amount, rate, and closing costs are recorded", autoCheck: "preapprovalTermsRecorded" },
    { id: "preapproval.c.expiry", label: "The expiration or refresh date is recorded", autoCheck: "preapprovalExpiryRecorded" },
  ],
  relatedTools: [
    { label: "Preapprovals", href: "/lenders?tab=approvals", description: "Track each approval level separately." },
    { label: "Financial guardrails", href: "/settings", description: "Our limits, which outrank the lender's." },
    { label: "Document index", href: "/timeline?tab=documents", description: "Note where the letter is stored." },
  ],
  order: 6,
  version: 1,
};

export const PLANNING_STAGES: GuideStage[] = [
  strategy,
  finances,
  attending,
  mortgageOptions,
  lenderInterviews,
  preapproval,
];
