import type { GuideStage } from "../types";

/**
 * Stages 7–11: choosing a buyer's agent, assembling the wider professional
 * team, researching towns, opening the active search, and touring.
 */

const agentSelection: GuideStage = {
  id: "agent-selection",
  number: 7,
  title: "Find and interview buyer's agents",
  shortTitle: "Buyer's agent",
  purpose:
    "Find an agent who represents our interests, knows our target markets, and can work across all of them.",
  explanation:
    "This is a hiring decision. Interview several candidates, verify concrete recent experience, and read the representation agreement before signing anything.",
  readinessAreas: ["team", "search"],
  suggestedWindow: { start: "2026-12", end: "2027-03" },
  warnings: [
    {
      tone: "caution",
      text: "The listing agent represents the seller unless a different agency arrangement has been explicitly established. Assume the agent at an open house is working for the other side.",
    },
  ],
  personalization: [
    {
      id: "agent-selection.none",
      when: "noAgentsInterviewed",
      text: "No agent interviews are recorded yet. Starting now means we can be selective rather than hiring whoever answers the phone when a listing appears.",
    },
    {
      id: "agent-selection.towns",
      when: "hasPrimaryTowns",
      text: "Our primary towns are {{primaryTowns}}. Ask every candidate for concrete recent buyer-side transactions in those specific towns.",
    },
    {
      id: "agent-selection.agreement",
      when: "agentSelectedWithoutAgreement",
      text: "We have selected an agent but the buyer-agreement terms are not recorded. Review the agreement's scope, duration, compensation, and termination before signing.",
    },
    {
      id: "agent-selection.price-band",
      when: "always",
      text: "Ask specifically what tradeoffs to expect in our towns at {{comfortableRange}} — a good agent will answer concretely and a weak one will answer vaguely.",
    },
  ],
  actions: [
    {
      id: "agent-selection.gather-candidates",
      title: "Gather candidates from several independent sources",
      why: "One referral is a sample of one. Several sources reveal who genuinely works our towns.",
      whatToGather:
        "Referrals from recent buyers we trust; attorneys, lenders and inspectors who work locally; agents with documented recent buyer-side sales in our towns; local brokerage and REALTOR® directories; names appearing on recent sold listings.",
      completionCriteria: "At least three candidates are recorded.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "agent-selection.verify-license",
      title: "Verify each candidate's New Jersey licence",
      why: "Two minutes of verification, and it establishes the brokerage relationship too.",
      whatToGather: "Licence number, status, and brokerage from the state licensee search.",
      defaultOwner: "buyer1",
      weight: 3,
    },
    {
      id: "agent-selection.verify-experience",
      title: "Verify recent buyer-side experience in our target towns",
      why: "Volume elsewhere does not transfer. We want specific, recent, buyer-side transactions where we are buying.",
      whatToGather: "Number of buyers represented in the last 12 months and transactions per target town.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "agent-selection.interview",
      title: "Interview at least three candidates",
      why: "The comparison is what makes a good candidate recognisable.",
      completionCriteria: "Three interviews are recorded with answers captured.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "agent-selection.references",
      title: "Speak with recent buyer clients",
      why: "Two conversations with recent buyers tell us more than any review page.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "agent-selection.compensation",
      title: "Discuss compensation explicitly",
      why: "Compensation is negotiable and the terms are ours to understand before signing.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "agent-selection.agreement-review",
      title: "Read the buyer representation agreement carefully",
      why: "Scope, duration, geography, compensation, and termination all matter, and all are negotiable.",
      whatToGather: "The full written agreement, before signing.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "agent-selection.scorecard",
      title: "Complete a scorecard for each candidate",
      why: "Ratings recorded straight after each interview beat a recollection a week later.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "agent-selection.decide",
      title: "Make and record the decision together",
      why: "This person will be in the room for the largest purchase we have made. Both of us should be convinced.",
      defaultOwner: "both",
      weight: 8,
    },
  ],
  decisions: [
    {
      id: "agent-selection.choice",
      prompt: "Which agent are we hiring, and what specifically convinced us?",
      help: "Do not simply pick the highest score. Write the reason in words.",
      requiresBothSpouses: true,
    },
    {
      id: "agent-selection.concerns",
      prompt: "What reservation do we still have about this agent, and how will we manage it?",
      requiresBothSpouses: true,
    },
    {
      id: "agent-selection.agreement-terms",
      prompt: "What agreement terms did we negotiate — duration, geography, compensation, termination?",
      requiresBothSpouses: true,
    },
  ],
  questionSets: [
    {
      audience: "agent",
      title: "Agent interview questions",
      intro: "Record answers on each candidate's record so the comparison is real rather than remembered.",
      questions: [
        { id: "agent.q.buyers-12mo", question: "How many buyers have you represented during the last 12 months?" },
        { id: "agent.q.transactions-towns", question: "How many transactions have you completed in each of our target towns?" },
        { id: "agent.q.towns-known", question: "Which of our preferred towns do you know deeply?" },
        { id: "agent.q.towns-recommended", question: "Which towns would you recommend at our budget, and why?" },
        { id: "agent.q.tradeoffs", question: "What tradeoffs should we expect around $1 million to $1.2 million?" },
        { id: "agent.q.comps", question: "How do you evaluate comparable sales?" },
        { id: "agent.q.offer-price", question: "How do you advise on offer price?" },
        { id: "agent.q.overbidding", question: "How do you protect buyers from emotional overbidding?", listenFor: "A concrete method, not reassurance." },
        { id: "agent.q.appraisal-gap", question: "How do you approach appraisal gaps?" },
        { id: "agent.q.inspection-limits", question: "How do you approach inspection limitations?" },
        { id: "agent.q.multiple-offers", question: "How do you handle multiple-offer situations?" },
        { id: "agent.q.availability", question: "What is your availability for weekday and weekend showings?" },
        { id: "agent.q.coverage", question: "Who covers for you when you are unavailable?" },
        { id: "agent.q.attend-showings", question: "Will you personally attend our showings?" },
        { id: "agent.q.response-time", question: "How quickly do you usually respond?" },
        { id: "agent.q.listings", question: "How will listings be sent to us?" },
        { id: "agent.q.conflicts", question: "Do you have relationships that create potential conflicts?" },
        { id: "agent.q.compensation", question: "How are you compensated?" },
        { id: "agent.q.seller-shortfall", question: "What happens if the seller does not cover the full compensation?" },
        { id: "agent.q.negotiable", question: "Is compensation negotiable?" },
        { id: "agent.q.agreement-requires", question: "What does your buyer representation agreement require?" },
        { id: "agent.q.agreement-length", question: "How long does the agreement last?" },
        { id: "agent.q.agreement-limits", question: "Can it be limited by geography or time?" },
        { id: "agent.q.termination", question: "How can either party terminate it?" },
        { id: "agent.q.references", question: "Can we speak with two recent buyer clients?" },
      ],
    },
  ],
  documents: [
    { label: "Buyer representation agreement", category: "buyer-agreement" },
    { label: "Licence verification screenshot or note", category: "identification" },
    { label: "Written compensation terms", category: "buyer-agreement" },
  ],
  resourceSlugs: [
    "nj-rec-licensee-search",
    "nar-questions-buyers-agent",
    "nar-written-buyer-agreements",
    "nar-agency-relationships",
  ],
  mistakes: [
    "Hiring the first agent referred to us without interviewing anyone else.",
    "Treating an agent's social-media presence or sales volume as proof of buyer representation quality.",
    "Signing a buyer agreement without reading the duration, geography, and termination terms.",
    "Assuming the agent at an open house is working for us.",
    "Picking the highest scorecard total instead of the person we actually trust to talk us out of a bad decision.",
    "Avoiding the compensation conversation because it feels awkward.",
  ],
  completionCriteria: [
    { id: "agent-selection.c.candidates", label: "At least three candidates were identified", autoCheck: "threeAgentCandidates" },
    { id: "agent-selection.c.interviews", label: "At least three candidates were interviewed", autoCheck: "threeAgentsInterviewed" },
    { id: "agent-selection.c.verified", label: "The chosen agent's licence and local experience are verified", autoCheck: "agentVerified" },
    { id: "agent-selection.c.agreement", label: "The buyer agreement terms are recorded and reviewed", autoCheck: "buyerAgreementReviewed" },
    { id: "agent-selection.c.decision", label: "Both of us have recorded the decision", autoCheck: "agentDecisionRecorded" },
  ],
  relatedTools: [
    { label: "Professionals", href: "/professionals?role=buyer-agent", description: "Candidates, interviews, verification, scorecards." },
    { label: "Town research", href: "/journey/town-research", description: "The towns to ask candidates about." },
    { label: "Resource library", href: "/resources", description: "Licence search and agency guides." },
  ],
  order: 7,
  version: 1,
};

const professionalTeam: GuideStage = {
  id: "professional-team",
  number: 8,
  title: "Build the professional team",
  shortTitle: "Professional team",
  purpose: "Line up the rest of the team before we need any of them urgently.",
  explanation:
    "In New Jersey the attorney-review clock and inspection deadlines are short. The people we will need are much easier to choose calmly, in advance.",
  readinessAreas: ["team", "offer"],
  suggestedWindow: { start: "2027-01", end: "2027-04" },
  personalization: [
    {
      id: "professional-team.gaps",
      when: "teamGapsExist",
      text: "Still unfilled: {{missingRoles}}. Each of these becomes urgent the moment an offer is accepted.",
    },
    {
      id: "professional-team.nj-specific",
      when: "always",
      text: "For older New Jersey housing stock, the sewer scope and underground oil-tank sweep are worth arranging in advance — they are the findings that most often change a deal.",
    },
  ],
  actions: [
    {
      id: "professional-team.attorney",
      title: "Identify a real-estate attorney",
      why: "Attorney review starts within days of contract signature. This is not the moment to start searching.",
      completionCriteria: "An attorney is recorded and selected.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "professional-team.home-inspector",
      title: "Identify a home inspector",
      why: "Good inspectors are booked out, and the inspection window is short.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "professional-team.sewer-inspector",
      title: "Identify a sewer-scope provider",
      why: "A collapsed lateral is a five-figure surprise that a standard inspection will not find.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "professional-team.oil-tank",
      title: "Identify an oil-tank sweep provider",
      why: "Buried tanks are common in older New Jersey homes and carry real remediation liability.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "professional-team.radon",
      title: "Identify a radon tester",
      why: "Radon testing takes days, which has to fit inside the inspection window.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "professional-team.structural-engineer",
      title: "Identify a structural engineer for follow-up",
      why: "When an inspector flags something structural, we need a specialist immediately, not next week.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "professional-team.insurance-agent",
      title: "Identify an insurance agent",
      why: "Insurability and cost can change whether a house is a good idea — and cannot be assumed.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "professional-team.contractor",
      title: "Identify a contractor for renovation estimates",
      why: "A real estimate beats a guess when deciding what a house will actually cost us.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "professional-team.title-company",
      title: "Note the title company and surveyor arrangements",
      why: "Usually coordinated by the attorney or lender, but worth knowing who they are.",
      defaultOwner: "attorney",
      weight: 2,
    },
    {
      id: "professional-team.record-fees",
      title: "Record fee estimates for the whole team",
      why: "These fees are part of the cash needed at closing and are easy to forget.",
      defaultOwner: "both",
      weight: 3,
    },
  ],
  decisions: [
    {
      id: "professional-team.attorney-choice",
      prompt: "Which attorney are we retaining, and what is their fee structure?",
      requiresBothSpouses: true,
    },
    {
      id: "professional-team.inspection-scope",
      prompt: "Which inspections will we order by default on any house we go under contract on?",
      suggestions: ["General", "Sewer scope", "Oil-tank sweep", "Radon", "Chimney", "Termite/pests"],
      requiresBothSpouses: true,
    },
  ],
  questionSets: [
    {
      audience: "attorney",
      title: "Attorney interview questions",
      questions: [
        { id: "attorney.q.volume", question: "How many New Jersey residential purchases do you handle each year?" },
        { id: "attorney.q.towns", question: "Do you regularly work in our target towns?" },
        { id: "attorney.q.fee", question: "What is your flat fee, and what does it exclude?" },
        { id: "attorney.q.review-speed", question: "How quickly do you turn around attorney review?" },
        { id: "attorney.q.contact", question: "Who is our day-to-day contact — you or a paralegal?" },
        { id: "attorney.q.issues", question: "What issues do you see most often in this area, and how do you handle them?" },
        { id: "attorney.q.availability", question: "What is your availability during our target closing window?" },
      ],
    },
    {
      audience: "inspector",
      title: "Inspector interview questions",
      questions: [
        { id: "inspector.q.license", question: "Are you licensed in New Jersey, and how long have you been inspecting?" },
        { id: "inspector.q.duration", question: "How long does a typical inspection of a house like ours take?" },
        { id: "inspector.q.attend", question: "May we attend and follow you through the house?" },
        { id: "inspector.q.report", question: "When do we get the report, and what does it look like?" },
        { id: "inspector.q.scope", question: "What is explicitly outside your scope?" },
        { id: "inspector.q.extras", question: "Do you provide sewer scope, radon, or oil-tank sweep, or do we book those separately?" },
        { id: "inspector.q.older-homes", question: "What do you find most often in older homes in this area?" },
      ],
    },
    {
      audience: "insurance",
      title: "Insurance questions",
      questions: [
        { id: "insurance.q.quote", question: "What would a policy cost on a house like this, in this town?" },
        { id: "insurance.q.flood", question: "Is flood insurance required or advisable here?" },
        { id: "insurance.q.claims", question: "Does the property's claims history affect our ability to insure it?" },
        { id: "insurance.q.age-issues", question: "Do the roof age, electrical panel, or oil tank create coverage problems?" },
      ],
    },
  ],
  documents: [
    { label: "Attorney engagement letter", category: "attorney-review" },
    { label: "Inspector credentials and sample report", category: "inspection" },
    { label: "Insurance quotes", category: "insurance" },
  ],
  resourceSlugs: ["nar-signing-to-closing", "nj-rec-licensee-search"],
  mistakes: [
    "Waiting until the offer is accepted to find an attorney.",
    "Using whoever the agent recommends without asking about the relationship.",
    "Skipping the sewer scope or oil-tank sweep on an older house to save a few hundred dollars.",
    "Forgetting that professional fees are cash needed at closing.",
    "Not checking insurability before committing to a house.",
  ],
  completionCriteria: [
    { id: "professional-team.c.attorney", label: "An attorney is selected", autoCheck: "attorneySelected" },
    { id: "professional-team.c.inspector", label: "A home inspector is selected", autoCheck: "inspectorSelected" },
    { id: "professional-team.c.specialists", label: "Sewer, oil-tank, and radon providers are identified", autoCheck: "specialistsIdentified" },
    { id: "professional-team.c.insurance", label: "An insurance contact is identified", autoCheck: "insuranceIdentified" },
  ],
  relatedTools: [
    { label: "Professionals", href: "/professionals", description: "The full directory with role checklists." },
    { label: "Inspection checklists", href: "/timeline", description: "Reusable checklists per inspection type." },
  ],
  order: 8,
  version: 1,
};

const townResearch: GuideStage = {
  id: "town-research",
  number: 9,
  title: "Research towns and schools",
  shortTitle: "Towns & schools",
  purpose: "Narrow the search before becoming attached to individual houses.",
  explanation:
    "Choosing the town well is most of the decision. A house can be changed; the commute, the taxes, and the assigned schools cannot.",
  readinessAreas: ["search"],
  suggestedWindow: { start: "2026-09", end: "2027-02" },
  personalization: [
    {
      id: "town-research.unvisited-primary",
      when: "primaryTownUnvisited",
      text: "A town is marked Primary without a recorded research visit. Visit it on a weekday and a weekend before it shapes our whole search.",
    },
    {
      id: "town-research.commute",
      when: "always",
      text: "Our commute limit is {{maxCommute}} door-to-door. Test it at the actual hour we would travel, including the walk and the station parking.",
    },
    {
      id: "town-research.school-threshold",
      when: "always",
      text: "Our school threshold is a research target, not a fact. Verify assignment with the district for the specific address — boundaries move.",
    },
  ],
  actions: [
    {
      id: "town-research.why-considering",
      title: "Record why we are considering each town",
      why: "Written reasons make it obvious later when a town no longer fits.",
      defaultOwner: "both",
      weight: 2,
    },
    {
      id: "town-research.price-and-taxes",
      title: "Record typical purchase price and property-tax burden per town",
      why: "New Jersey tax bills vary enough between towns to change the monthly payment by thousands.",
      whatToGather: "Recent sold prices matching our criteria and actual tax bills from listings.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "town-research.commute-test",
      title: "Test the real door-to-door commute",
      why: "Timetables measure the train, not the morning.",
      whatToGather: "Station, line, parking availability, permit rules, and the total door-to-door time.",
      completionCriteria: "A door-to-door time is recorded for each primary town.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "town-research.station-parking",
      title: "Check station parking and permit restrictions",
      why: "A multi-year permit waiting list can quietly make a commute unworkable.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "town-research.schools",
      title: "Verify how school assignment actually works in each town",
      why: "Assignment is address-specific and cannot be inferred from a town's reputation.",
      whatToGather: "The district's assignment lookup method and what we used to verify it.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "town-research.childcare",
      title: "Check childcare availability",
      why: "Availability, not just cost, decides whether a town works for us.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "town-research.healthcare",
      title: "Check healthcare access and hospital proximity",
      why: "Relevant to both daily life and a physician's commute.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "town-research.flood",
      title: "Review flood considerations",
      why: "Flood exposure affects insurance cost, availability, and resale.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "town-research.housing-stock",
      title: "Record housing stock, typical home age, and lot sizes",
      why: "It tells us what our budget actually buys before we tour anything.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "town-research.renovation-patterns",
      title: "Note local renovation patterns and ordinances that matter",
      why: "Permit history and local rules affect what we could change after buying.",
      defaultOwner: "both",
      weight: 2,
    },
    {
      id: "town-research.visit",
      title: "Visit each candidate town on a weekday and a weekend",
      why: "A town feels different at 8am Tuesday than at 11am Saturday. A town may not be promoted to Primary without a visit.",
      completionCriteria: "A visit date and both impressions are recorded.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "town-research.strengths-weaknesses",
      title: "Write the strengths, weaknesses, and budget fit for each town",
      why: "This is what turns a long list into a short one.",
      defaultOwner: "both",
      weight: 5,
    },
  ],
  decisions: [
    {
      id: "town-research.primary-list",
      prompt: "Which towns are Primary, and what makes each one primary rather than backup?",
      requiresBothSpouses: true,
    },
    {
      id: "town-research.ruled-out",
      prompt: "Which towns have we ruled out, and for what specific reason?",
      help: "Recording the reason stops us from relitigating it every few weeks.",
    },
  ],
  questionSets: [
    {
      audience: "agent",
      title: "Town questions for our agent",
      questions: [
        { id: "town.q.inventory", question: "What does our budget realistically buy in this town right now?" },
        { id: "town.q.turnover", question: "How quickly do houses like ours move here, and at what over- or under-ask?" },
        { id: "town.q.taxes", question: "How do assessments and tax appeals typically work in this town?" },
        { id: "town.q.pockets", question: "Are there streets or pockets that behave differently from the town average?" },
        { id: "town.q.schools", question: "How do buyers here verify school assignment for a specific address?" },
      ],
    },
  ],
  documents: [
    { label: "School assignment verification for each town", category: "property-disclosures" },
    { label: "Property tax examples from listings", category: "property-disclosures" },
  ],
  resourceSlugs: ["hud-buying-a-home", "cfpb-owning-a-home"],
  mistakes: [
    "Promoting a town to Primary based on reputation alone.",
    "Trusting a listing's school claim instead of the district's own assignment tool.",
    "Testing the commute at a convenient hour rather than the real one.",
    "Ignoring station permit waiting lists.",
    "Comparing towns on price without comparing tax bills.",
  ],
  completionCriteria: [
    { id: "town-research.c.primary", label: "At least two towns are marked Primary", autoCheck: "twoPrimaryTowns" },
    { id: "town-research.c.visited", label: "Every Primary town has a recorded research visit", autoCheck: "primaryTownsVisited" },
    { id: "town-research.c.commute", label: "Door-to-door commute is recorded for each Primary town", autoCheck: "primaryTownsCommuteRecorded" },
    { id: "town-research.c.backup", label: "At least one backup town is identified", autoCheck: "backupTownIdentified" },
  ],
  relatedTools: [
    { label: "Town research", href: "/journey/town-research", description: "On this page, below." },
    { label: "Home preferences", href: "/settings", description: "Commute and school requirements." },
    { label: "Properties", href: "/properties", description: "See what each town actually produced." },
  ],
  order: 9,
  version: 1,
};

const activeSearch: GuideStage = {
  id: "active-search",
  number: 10,
  title: "Begin the active property search",
  shortTitle: "Active search",
  purpose:
    "Start searching in earnest only once the financial limits, financing strategy, and team are substantially ready.",
  explanation:
    "Touring before we are ready is how people end up making an emotional offer on the third house they see. Nothing here blocks us — but the gaps are shown plainly.",
  readinessAreas: ["search", "offer"],
  suggestedWindow: { start: "2027-01", end: "2027-05" },
  personalization: [
    {
      id: "active-search.not-ready",
      when: "searchReadinessIncomplete",
      text: "Some readiness items are still open. We can start anyway, but the missing pieces below are the ones that cost buyers houses.",
    },
    {
      id: "active-search.ready",
      when: "searchReadinessComplete",
      text: "The readiness requirements are met. We can search with our limits and our team already in place.",
    },
  ],
  actions: [
    {
      id: "active-search.confirm-guardrails",
      title: "Confirm financial guardrails are established",
      why: "The guardrails are what keep the search from drifting upward one listing at a time.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "active-search.confirm-house-fund",
      title: "Confirm the house fund is identified and available",
      why: "Knowing the exact cash available makes offers decisive.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "active-search.confirm-lender-strategy",
      title: "Confirm the lender strategy is complete",
      why: "Including how the attending contract will be treated.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "active-search.confirm-preapproval",
      title: "Confirm a preapproval is available or in progress",
      why: "Most sellers will not consider an offer without one.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "active-search.confirm-agent",
      title: "Confirm our agent is selected and the agreement is understood",
      why: "Our representation should be settled before we walk into someone else's listing.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "active-search.confirm-towns",
      title: "Confirm primary and backup towns are selected",
      why: "It focuses both the search alerts and the agent's effort.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "active-search.confirm-criteria",
      title: "Confirm must-haves, deal-breakers, and renovation tolerance are approved",
      why: "These are the filters we will lean on when a listing is tempting but wrong.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "active-search.confirm-commute",
      title: "Confirm commute assumptions are documented",
      why: "So a listing can be dismissed on commute grounds without relitigating it each time.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "active-search.set-up-alerts",
      title: "Set up listing alerts with our agent",
      why: "In our price range, good houses move quickly. Being early matters more than being clever.",
      defaultOwner: "agent",
      weight: 3,
    },
    {
      id: "active-search.viewing-rhythm",
      title: "Agree a sustainable viewing rhythm",
      why: "Exhausted buyers make worse decisions than patient ones.",
      defaultOwner: "both",
      weight: 2,
    },
  ],
  decisions: [
    {
      id: "active-search.start-date",
      prompt: "When do we start touring in earnest, and what has to be true first?",
      requiresBothSpouses: true,
    },
    {
      id: "active-search.pace",
      prompt: "How many houses will we see per week, and who schedules them?",
    },
  ],
  questionSets: [
    {
      audience: "agent",
      title: "Search setup questions",
      questions: [
        { id: "search.q.alerts", question: "How will we hear about a new listing, and how fast?" },
        { id: "search.q.pre-market", question: "How do you handle coming-soon and pre-market listings?" },
        { id: "search.q.same-day", question: "Can we see a house the day it lists if we need to?" },
        { id: "search.q.filter", question: "Which listings will you filter out for us, and on what basis?" },
      ],
    },
  ],
  documents: [
    { label: "Current preapproval letter, ready to send", category: "preapproval" },
    { label: "Proof of funds, ready to send", category: "bank-statements" },
  ],
  resourceSlugs: ["hud-buying-a-home", "cfpb-preapproval-letter"],
  mistakes: [
    "Touring before the walk-away price exists.",
    "Starting without a preapproval and losing the first good house.",
    "Letting the search quietly expand above the comfortable range.",
    "Seeing so many houses that judgment blurs.",
    "Falling for the first house because it is the only one seen.",
  ],
  completionCriteria: [
    { id: "active-search.c.guardrails", label: "Financial guardrails are established", autoCheck: "guardrailsComplete" },
    { id: "active-search.c.fund", label: "The house fund is identified", autoCheck: "houseFundIdentified" },
    { id: "active-search.c.preapproval", label: "A preapproval exists or is in progress", autoCheck: "preapprovalInProgress" },
    { id: "active-search.c.agent", label: "An agent is selected", autoCheck: "agentSelected" },
    { id: "active-search.c.towns", label: "Primary and backup towns are selected", autoCheck: "townStrategyDocumented" },
    { id: "active-search.c.criteria", label: "Must-haves, deal-breakers, and renovation tolerance are approved", autoCheck: "criteriaApproved" },
  ],
  relatedTools: [
    { label: "Properties", href: "/properties", description: "The tracker for everything we see." },
    { label: "Compare", href: "/compare", description: "Side-by-side once a shortlist forms." },
    { label: "Financial planner", href: "/finances", description: "Test a listing price in seconds." },
  ],
  order: 10,
  version: 1,
};

const touring: GuideStage = {
  id: "touring",
  number: 11,
  title: "Tour and evaluate properties",
  shortTitle: "Touring",
  purpose: "See houses carefully, and record what we saw before enthusiasm rewrites it.",
  explanation:
    "The most valuable ten minutes of any tour happen in the car afterwards, while the details are still accurate.",
  readinessAreas: ["search", "offer"],
  suggestedWindow: { start: "2027-01", end: "2027-05" },
  personalization: [
    {
      id: "touring.no-preapproval",
      when: "touringWithoutPreapproval",
      text: "We are touring without a recorded preapproval. If we find the right house this week, we may not be able to act on it.",
    },
    {
      id: "touring.unreviewed",
      when: "visitsPendingNotes",
      text: "There are visited properties without completed notes. Finish those before the next tour — memories blur faster than expected.",
    },
  ],
  actions: [
    {
      id: "touring.use-visit-mode",
      title: "Use Visit mode during every showing",
      why: "Structured notes on the spot beat impressions recalled that evening.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "touring.record-both-opinions",
      title: "Record both of our opinions separately",
      why: "Recording separately surfaces genuine disagreement instead of averaging it away.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "touring.verify-commute",
      title: "Verify the commute from the actual address",
      why: "Two streets can differ by fifteen minutes and a parking permit.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "touring.verify-schools",
      title: "Verify assigned schools for the specific address",
      why: "Assignment is by address, not by town, and boundaries change.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "touring.verify-taxes",
      title: "Verify the actual property tax bill",
      why: "The listing figure is often stale or wrong, and the difference lands in the monthly payment.",
      defaultOwner: "both",
      weight: 8,
    },
    {
      id: "touring.run-numbers",
      title: "Run the full cost estimate before the next showing",
      why: "It is much easier to walk away from a house before we have seen three more.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "touring.post-tour-reflection",
      title: "Complete the post-tour reflection questions",
      why: "These are the questions that catch a compromise we would regret.",
      defaultOwner: "both",
      weight: 5,
    },
    {
      id: "touring.shortlist",
      title: "Shortlist deliberately",
      why: "A shortlist of everything is not a shortlist.",
      defaultOwner: "both",
      weight: 3,
    },
    {
      id: "touring.second-visit",
      title: "Visit any serious contender a second time",
      why: "The second visit is when the house is seen rather than felt.",
      defaultOwner: "both",
      weight: 5,
    },
  ],
  decisions: [
    {
      id: "touring.compromise",
      prompt: "Which compromise are we making on this house, and will it still be acceptable in five years?",
      requiresBothSpouses: true,
    },
    {
      id: "touring.excitement",
      prompt: "Would we still want this house after the excitement wears off?",
      help: "Answer honestly, in writing, before discussing an offer.",
      requiresBothSpouses: true,
    },
  ],
  questionSets: [
    {
      audience: "ourselves",
      title: "After every tour, before the next one",
      questions: [
        { id: "touring.q.before-entering", question: "What did we notice before entering?" },
        { id: "touring.q.overlooked", question: "What did we overlook because we liked the house?" },
        { id: "touring.q.compromise", question: "Which compromise are we making?" },
        { id: "touring.q.five-years", question: "Will this compromise matter in five years?" },
        { id: "touring.q.excitement", question: "Would we still want this house after the excitement wears off?" },
      ],
    },
    {
      audience: "agent",
      title: "Questions at the showing",
      questions: [
        { id: "touring.q.days-on-market", question: "How long has it been listed, and have there been price changes?" },
        { id: "touring.q.why-selling", question: "Why is the seller selling, and what is their timeline?" },
        { id: "touring.q.offers", question: "Have there been offers, and what happened to them?" },
        { id: "touring.q.work-done", question: "What work has been done, and were permits pulled?" },
        { id: "touring.q.disclosures", question: "What do the disclosures say?" },
      ],
    },
  ],
  documents: [
    { label: "Listing sheet and seller disclosures", category: "property-disclosures" },
    { label: "Actual property tax bill", category: "property-disclosures" },
    { label: "School assignment confirmation", category: "property-disclosures" },
  ],
  resourceSlugs: ["hud-buying-a-home"],
  mistakes: [
    "Touring another house before writing up the last one.",
    "Trusting the listing's tax figure.",
    "Assuming the school from the town name.",
    "Overlooking a deal-breaker because the kitchen is beautiful.",
    "Making an offer after one visit.",
  ],
  completionCriteria: [
    { id: "touring.c.notes", label: "Every visited property has completed notes", autoCheck: "allVisitsDocumented" },
    { id: "touring.c.shortlist", label: "A shortlist exists", autoCheck: "shortlistExists" },
    { id: "touring.c.verified", label: "Shortlisted properties have verified taxes, schools, and commute", autoCheck: "shortlistVerified" },
  ],
  relatedTools: [
    { label: "Properties", href: "/properties", description: "The tracker and per-property estimates." },
    { label: "Visit mode", href: "/properties", description: "Open a property, then start a visit." },
    { label: "Compare", href: "/compare", description: "Two to five properties side by side." },
  ],
  order: 11,
  version: 1,
};

export const TEAM_STAGES: GuideStage[] = [
  agentSelection,
  professionalTeam,
  townResearch,
  activeSearch,
  touring,
];
